services:
    app:
        extends:
            file: docker-compose.yml
            service: app
        build:
            target: build-production
        image: app:production

    caddy:
        extends:
            file: docker-compose.yml
            service: caddy
        volumes:
            - ./build/prod/Caddyfile:/etc/caddy/Caddyfile:ro
        healthcheck:
            test: ["CMD", "wget", "--spider", "https://acme.com/healthcheck"]
