services:
    app:
        build:
            target: build-development
        image: app:development
        volumes:
            - ./coverage:/coverage

    caddy:
        volumes:
            - ./build/dev/Caddyfile:/etc/caddy/Caddyfile:ro
        healthcheck:
            test: ["CMD", "wget", "--spider", "https://website.localhost/healthcheck"]
