services:
    caddy:
        environment:
            - HOSTNAME=website.localhost
            - PHP_FPM_GATEWAYS=app1:9000 app2:9000
        healthcheck:
            test: ["CMD", "wget", "--spider", "https://website.localhost/healthcheck"]
        depends_on:
            - app1
            - app2

    app2:
        extends:
            file: docker-compose.yml
            service: app1
        container_name: app2
