volumes:
    caddy_data:
    caddy_config:

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/var/www/html

    caddy:
        container_name: caddy
        image: caddy:2.8.4-alpine
        restart: unless-stopped
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./src:/var/www/html
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        healthcheck:
            interval: 10s
            timeout: 1s
            retries: 3
        depends_on:
            - app
