services:
    app:
        extends:
            file: docker-compose.yml
            service: app
        build:
            target: build-development
        image: app:development
        volumes:
            - ./coverage:/coverage

    caddy:
        extends:
            file: docker-compose.yml
            service: caddy
        volumes:
            - ./build/dev/Caddyfile:/etc/caddy/Caddyfile:ro
        healthcheck:
            test: ["CMD", "wget", "--spider", "https://website.localhost/healthcheck"]
