name: Continuous Integration

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

permissions:
    contents: read

jobs:
    testsuite:
        name: Testsuite

        runs-on: ubuntu-latest

        env:
            ENV: DEVELOPMENT

        steps:
            - name: Build the Docker image
              run: docker build --file Dockerfile --target build-development .
